### ISSUE TITLE
Folding comments/cells

### ISSUE THREAD

**Issue by argapost** [eddiebergman/nvim-treesitter-pyfold#1]
Hello! 

I was wondering if it is possible to fold everything below a specific pattern (# %%) that defines a "cell" similar to matlab. Here is an image for example:

![image](https://user-images.githubusercontent.com/58076098/144261660-6f475393-319c-4f18-8eb8-7c2a7d6b149a.png)

Thank you in advance!

**Comment by eddiebergman** [comment]
Hi @argapost, 

Thanks for your interest! I don't think this is directly possible with treesitter, or at least not to my knowledge. The reason being (I could be wrong) is that a comment like that is a leaf of the syntax tree, meaning there is nothing underneath it to fold.

See the [gif of nvim-treesitter-playground](https://github.com/nvim-treesitter/playground#neovim-treesitter-playground) (right side) and you'll see what I mean by "underneath". In contrast, a function has expressions, documentation and many other possible things "underneath" it.

**Comment by argapost** [comment]
Thanks for the quick response! I understand, I tried myself to implement it but without any luck, thought a smarter person might find a way but yeah there is nothing in the tree regarding the comments.
