### ISSUE TITLE
Cannot separately fold docstrings from method/class body 

### ISSUE THREAD

**Issue by erik-samuelsson** [eddiebergman/nvim-treesitter-pyfold#2]
Hi, neat plugin! However I cannot seem to open and fold docs separately of the body.

I'm including relevant parts of my init.lua and lua/plugins.lua

init.lua:
```
-- vim.o.foldmethod="expr"
-- vim.o.foldexpr = 'nvim_treesitter#foldexpr()'
require'nvim-treesitter.configs'.setup{
  highlight = {
    enable = true
  },
  matchup = {
    enable = true, 
  },
  incremental_selection = {
    enable = true, 
    init_selection = "gnn",
    node_incremental = "grn",
    scope_incremental = "grc",
    node_decremental = "grm"
  },
  pyfold = {
    enable = true,
    custom_foldtext = true
  }
}
```

lua/plugins.lua:

```
return require('packer').startup(function()
  use 'wbthomason/packer.nvim'
  use {'dracula/vim', as='dracula'}
  use 'w0rp/ale'
  use {'averms/black-nvim', config=[[vim.cmd :UpdateRemotePlugin]]}
  use {'stsewd/isort.nvim', config=[[vim.cmd :UpdateRemotePlugin]]}
  use 'andviro/flake8-vim'
  use 'andymass/vim-matchup'
  --use 'scrooloose/nerdcommenter'
  use 'terrortylor/nvim-comment'
  use {'junegunn/fzf', dir='$HOME/.fzf', run='./install --all'}
  use 'junegunn/fzf.vim'
  use 'tpope/vim-surround'
  use 'neovim/nvim-lspconfig'
  use 'hrsh7th/cmp-nvim-lsp'
  use 'hrsh7th/cmp-buffer'
  use 'hrsh7th/cmp-path'
  use 'hrsh7th/cmp-cmdline'
  use {'hrsh7th/nvim-cmp' }
  use 'saadparwaiz1/cmp_luasnip'
  use{ 'L3MON4D3/LuaSnip', 
    config = function() require("config.snippets")end,
  }
  use "rafamadriz/friendly-snippets"
  use { 'nvim-treesitter/nvim-treesitter', run = ':TSUpdate' }
  use 'eddiebergman/nvim-treesitter-pyfold'
end)

```

Any idea why they keep folding together?

**Comment by eddiebergman** [comment]
Hey @erik-samuelsson, thanks for using the plugin!

I'm not quite sure what you mean? The only limitation I can think of that you're facing is that you want to have the docs open but not the body, which is not possible.

It will also unfold the docstring if it's only one line long as this takes up the same amount of space as if it was folded.

There's also a limitation that hitting 'fold' while on the body of the text will fold up the documentation and the body together.

Are one of these three things you problem? If you want the documentation and body to act as seperate folds that aren't tied together, you'll end up with two sections of fold text under the function definition, which seems more annoying to me personally. I could possibly add it as an option.


When folded fully:
![folded](https://user-images.githubusercontent.com/15933394/154717328-d9bd663e-4d80-4a44-b67a-f4d42acb3c7d.jpg)

Hitting unfold once on the fold text:
![unfolded_once](https://user-images.githubusercontent.com/15933394/154717326-295ac284-6dc1-4383-b1a6-ddd2fa6c5f37.jpg)

Hitting unfold on the documentation:
![unfolded_all](https://user-images.githubusercontent.com/15933394/154717320-66172fd9-18b5-4703-98d7-c71ad85a5bc7.jpg)

**Comment by erik-samuelsson** [comment]
Thank you for such a quick response! 

My hope was to be able to fold the docs while working on the body which is currently not possible in my case. 

Hitting fold on the documentation:
<img width="714" alt="Screenshot 2022-02-20 at 08 58 03" src="https://user-images.githubusercontent.com/98960178/154833915-454794b1-192f-4691-9c8f-4705f293cd4b.png">

After hitting fold: 
<img width="448" alt="Screenshot 2022-02-20 at 08 58 19" src="https://user-images.githubusercontent.com/98960178/154833924-1045ab17-3fe9-45f7-b71b-cd022c03b8ae.png">

The intention, to be clear is that the __init__ method would not fold with documentation.

Is it clear what I am trying to do and in what way it is failing?

**Comment by eddiebergman** [comment]
Ahh, so this should be the intended behaviour. The problem might be to do with the newlines, generally the python docstrongs have no newline between itself and the function/class definition. The example you show does have the newlines so I'm not sure if that's usually how you write it. In any case, I should probably account for it but your desired behaviour should work without the newline between.

If this is still not the case, then it's a real bug and I would have no idea why.

**Comment by erik-samuelsson** [comment]
Hmm... Tried playing around with newlines a bit between docs and def/class lines and the body but to no avail :) I will live with it! Should I figure out what's wrong or find a workaround I will post it here!

**Comment by eddiebergman** [comment]
Hmm, I'm sorry to hear.

**If other's have the same issue, please drop a comment**

Some other ideas that might help you:
* I use `noremap <space> zs` for folding and unfolding, it only folds/unfolds one level.
* The folds are actually defined [here](https://github.com/eddiebergman/nvim-treesitter-pyfold/blob/master/queries/python/folds.scm). You can play around [tree-sitter playground](https://github.com/nvim-treesitter/playground) to see what these different sections target, as that's how I was debugging things when making this. You can always fork this repo or install locally to try out different folds that suit your needs. If you let me know how you fixed your problem in relation to that, I'd be greatly appreciative :)

I'll keep this issue open anywho, in case other's have the same issue.

Best,
Eddie

**Comment by erik-samuelsson** [comment]
I found a workaround, indenting docstring body with respect to triple quote allowed for folding :) Not ideal(?) will. have to see if it influences our Sphinx workflow... 

But perhaps this means that there is some indent-based setting which is interfering?

**Comment by eddiebergman** [comment]
Could you provide a quick view of that?

```python
class A:
    """
        Do you have to do this?
    """

class B:
    """P.s. the fold text was designed around this line being useful short text :)
    
    Or is this okay?
    """

```

**Comment by eddiebergman** [comment]
Another P.s., a nice recent enough plugin you might enjoy for Sphinx
* https://github.com/danymat/neogen

**Comment by erik-samuelsson** [comment]
Class A is the only example which works for me, an example would be of the same with more indented lines. Class B does not :(

**Comment by eddiebergman** [comment]
That's weird, I'm going to close this issue and reopen an issue with that more clear example of what works and doesn't :)

**Comment by eddiebergman** [comment]
Sorry last idea, did you update your Treesitter parsers with `:TSUpdate`?

**Comment by eddiebergman** [comment]
... more idea's, what's you `foldmethod` once in a python file? It should be `expr`

```
set foldmethod  # expr
set foldexpr  # nvim_treesitter#foldexpr()
```

**Comment by erik-samuelsson** [comment]
My issue was solved when setting `foldexpr=nvim_treesitter#foldexpr()` in ~/.config/nvim/ftplugin/python.vim as you suggested!
